---
- name : Install Plugins
  shell: "ibmcloud plugin install -f -r "Bluemix" {{ items }}"
  with_items:
    - cloud-object-storage
    - container-registry
    - container-service
    - dev
    - logging-cli
    - doi/doi
  register: cli
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu" or ansible_distribution == 'Linux Mint'